title: <p align="center"> Niteesh Kumar Veldandi
logo: /assets/img/logo.png
description:
  <p align="center">|
  <a href="https://www.linkedin.com/in/niteeshkumarveldandi/">LinkedIn</a> |
  <a href="https://github.com/nittu1999">GitHub</a>
  
  <br>   
  I'm a full time stock market trader.
  <br>
  </p>

theme: jekyll-theme-minimal
